version: '3'

services:

  controller-service:
    build: 
      context: ./../controller-service
      dockerfile: ./../controller-service/controller-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable"

  users-services:
    build:
      context: ./../users-info-service
      dockerfile: ./../users-info-service/users-info-service.Dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable"
  
  trasanction-service:
    build: 
      context: ./../transaction-service
      dockerfile: ./../transaction-service/transaction-service.Dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable" 
  
  bank-service:
    build: 
      context: ./../fake-bank-service
      dockerfile: ./../fake-bank-service/fake-bank-service.Dockerfile
    restart: always
    ports:
      - "8083:80"
    
  wallet-service:
    build: 
      context: ./../wallet-service
      dockerfile: ./../wallet-service/wallet-service.Dockerfile
    restart: always
    ports:
      - "8084:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable" 


  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    


      